import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

export const supportedLanguages = ['en', 'hi', 'mr', 'bn', 'ta', 'te', 'gu', 'kn', 'ml'] as const;
export type LanguageCode = typeof supportedLanguages[number];

const en = {
  nav: { home: 'Home', trips: 'Trips', assistant: 'Assistant', bookings: 'Bookings', explore: 'Explore', about: 'About', food: 'Food', activities: 'Activities', lostFound: 'Lost & Found', saved: 'Saved Places', profile: 'Profile', settings: 'Settings', workspace: 'Workspace', plan: 'Plan a New Trip', logout: 'Log out', login: 'Log in' },
  common: { loading: 'Loading…', saveChanges: 'Save changes', cancel: 'Cancel', close: 'Close', search: 'Search', filters: 'Filters', language: 'Language', notifications: 'Notifications', noNotifications: 'No new notifications', caughtUp: 'You are all caught up.', account: 'Account', security: 'Security', appearance: 'Appearance', privacy: 'Privacy', travelPreferences: 'Travel Preferences', email: 'Email', password: 'Password', name: 'Name', submit: 'Submit', back: 'Back', next: 'Next', edit: 'Edit', delete: 'Delete' },
  pages: { dashboard: 'Dashboard', explore: 'Explore Destinations', planner: 'Plan your trip', itinerary: 'Your Personalized Trip', trips: 'My Trips', bookings: 'My Bookings', food: 'Food & Restaurants', activities: 'Activities & Experiences', lostFound: 'Lost & Found', saved: 'Saved Places', profile: 'Profile', settings: 'Settings', assistant: 'ATLAS Assistant', authWelcome: 'Welcome back', authCreate: 'Create your ATLAS account' },
  profile: { accountInfo: 'Account Information', fullName: 'Full Name', emailAddress: 'Email Address', phone: 'Phone Number', dob: 'Date of Birth', nationality: 'Nationality', editProfile: 'Edit Profile', cancelEditing: 'Cancel editing', preferences: 'Travel Preferences', foodPreference: 'Food preference', preferredLanguage: 'Preferred language', travelStyle: 'Travel style', accommodation: 'Accommodation preference', transport: 'Transport preference', budget: 'Budget preference', accessibility: 'Accessibility needs', savePreferences: 'Save preferences', updated: 'Profile updated', invalid: 'Check your details' },
  settings: { description: 'Control your account, appearance, language and privacy.', languageDescription: 'Choose the language used throughout the ATLAS interface.', displayName: 'Display name', homeCity: 'Home city', currency: 'Default currency', currentPassword: 'Current password', newPassword: 'New password', updatePassword: 'Update password', notifications: 'Notifications', travelDefaults: 'Travel Preferences', saveDefaults: 'Save defaults' },
  auth: { synced: 'Your trips and saved places stay synced across sessions.', register: 'Register', continueWith: 'or continue with', google: 'Continue with Google' },
  toast: { languageUpdated: 'Language updated', languageSaved: 'Interface language preference saved.' }
} as const;

// Every locale deliberately has the same key shape as English.  English is also
// configured as fallbackLng, so a future incomplete addition remains readable.
const localized: Record<Exclude<LanguageCode, 'en'>, Record<string, unknown>> = {
  hi: { nav: { home: 'होम', trips: 'यात्राएँ', assistant: 'सहायक', bookings: 'बुकिंग', explore: 'खोजें', about: 'परिचय', food: 'भोजन', activities: 'गतिविधियाँ', lostFound: 'खोया और पाया', saved: 'सहेजे गए स्थान', profile: 'प्रोफ़ाइल', settings: 'सेटिंग्स', workspace: 'कार्यस्थान', plan: 'नई यात्रा बनाएँ', logout: 'लॉग आउट', login: 'लॉग इन' }, common: { loading: 'लोड हो रहा है…', saveChanges: 'परिवर्तन सहेजें', cancel: 'रद्द करें', close: 'बंद करें', search: 'खोजें', filters: 'फ़िल्टर', language: 'भाषा', notifications: 'सूचनाएँ', noNotifications: 'कोई नई सूचना नहीं', caughtUp: 'आप सब देख चुके हैं।', account: 'खाता', security: 'सुरक्षा', appearance: 'दिखावट', privacy: 'गोपनीयता', travelPreferences: 'यात्रा प्राथमिकताएँ', email: 'ईमेल', password: 'पासवर्ड', name: 'नाम', submit: 'जमा करें', back: 'वापस', next: 'अगला', edit: 'संपादित करें', delete: 'हटाएँ' }, pages: { dashboard: 'डैशबोर्ड', explore: 'गंतव्य खोजें', planner: 'अपनी यात्रा बनाएँ', itinerary: 'आपकी व्यक्तिगत यात्रा', trips: 'मेरी यात्राएँ', bookings: 'मेरी बुकिंग', food: 'भोजन और रेस्तरां', activities: 'गतिविधियाँ और अनुभव', lostFound: 'खोया और पाया', saved: 'सहेजे गए स्थान', profile: 'प्रोफ़ाइल', settings: 'सेटिंग्स', assistant: 'ATLAS सहायक', authWelcome: 'फिर से स्वागत है', authCreate: 'अपना ATLAS खाता बनाएँ' }, profile: { accountInfo: 'खाता जानकारी', fullName: 'पूरा नाम', emailAddress: 'ईमेल पता', phone: 'फ़ोन नंबर', dob: 'जन्म तिथि', nationality: 'राष्ट्रीयता', editProfile: 'प्रोफ़ाइल संपादित करें', cancelEditing: 'संपादन रद्द करें', preferences: 'यात्रा प्राथमिकताएँ', foodPreference: 'भोजन संबंधी पसंद', preferredLanguage: 'पसंदीदा भाषा', travelStyle: 'यात्रा शैली', accommodation: 'ठहरने की पसंद', transport: 'परिवहन पसंद', budget: 'बजट पसंद', accessibility: 'सुलभता की ज़रूरतें', savePreferences: 'प्राथमिकताएँ सहेजें', updated: 'प्रोफ़ाइल अपडेट हुई', invalid: 'अपनी जानकारी जाँचें' }, settings: { description: 'अपना खाता, दिखावट, भाषा और गोपनीयता नियंत्रित करें।', languageDescription: 'ATLAS इंटरफ़ेस में उपयोग की जाने वाली भाषा चुनें।', displayName: 'दिखाया जाने वाला नाम', homeCity: 'गृह नगर', currency: 'डिफ़ॉल्ट मुद्रा', currentPassword: 'वर्तमान पासवर्ड', newPassword: 'नया पासवर्ड', updatePassword: 'पासवर्ड अपडेट करें', notifications: 'सूचनाएँ', travelDefaults: 'यात्रा प्राथमिकताएँ', saveDefaults: 'डिफ़ॉल्ट सहेजें' }, auth: { synced: 'आपकी यात्राएँ और सहेजे स्थान सत्रों में समन्वित रहते हैं।', register: 'पंजीकरण करें', continueWith: 'या जारी रखें', google: 'Google से जारी रखें' }, toast: { languageUpdated: 'भाषा अपडेट हुई', languageSaved: 'इंटरफ़ेस भाषा प्राथमिकता सहेजी गई।' } },
  mr: { nav: { home: 'मुख्यपृष्ठ', trips: 'सहली', assistant: 'सहाय्यक', bookings: 'बुकिंग', explore: 'शोधा', about: 'माहिती', food: 'अन्न', activities: 'उपक्रम', lostFound: 'हरवले व सापडले', saved: 'जतन केलेली ठिकाणे', profile: 'प्रोफाइल', settings: 'सेटिंग्ज', workspace: 'कार्यस्थान', plan: 'नवीन सहल आखा', logout: 'लॉग आउट', login: 'लॉग इन' }, pages: { profile: 'प्रोफाइल', settings: 'सेटिंग्ज', planner: 'तुमची सहल आखा', trips: 'माझ्या सहली', explore: 'स्थळे शोधा', assistant: 'ATLAS सहाय्यक' }, profile: { accountInfo: 'खाते माहिती', fullName: 'पूर्ण नाव', foodPreference: 'अन्न पसंती', preferences: 'प्रवास प्राधान्ये', savePreferences: 'प्राधान्ये जतन करा' } },
  bn: { nav: { home: 'হোম', trips: 'ভ্রমণ', assistant: 'সহকারী', bookings: 'বুকিং', explore: 'অন্বেষণ', profile: 'প্রোফাইল', settings: 'সেটিংস', food: 'খাবার', activities: 'কার্যকলাপ', lostFound: 'হারানো ও পাওয়া', saved: 'সংরক্ষিত স্থান', plan: 'নতুন ভ্রমণ পরিকল্পনা করুন' }, pages: { profile: 'প্রোফাইল', settings: 'সেটিংস', planner: 'আপনার ভ্রমণ পরিকল্পনা করুন', trips: 'আমার ভ্রমণ', explore: 'গন্তব্য অন্বেষণ' } },
  ta: { nav: { home: 'முகப்பு', trips: 'பயணங்கள்', assistant: 'உதவியாளர்', bookings: 'முன்பதிவுகள்', explore: 'ஆராய்', profile: 'சுயவிவரம்', settings: 'அமைப்புகள்', food: 'உணவு', activities: 'செயல்பாடுகள்', lostFound: 'தொலைந்தவை', saved: 'சேமித்த இடங்கள்', plan: 'புதிய பயணத்தைத் திட்டமிடு' }, pages: { profile: 'சுயவிவரம்', settings: 'அமைப்புகள்', planner: 'உங்கள் பயணத்தைத் திட்டமிடு', trips: 'என் பயணங்கள்', explore: 'இடங்களை ஆராய்' } },
  te: { nav: { home: 'హోమ్', trips: 'ప్రయాణాలు', assistant: 'సహాయకుడు', bookings: 'బుకింగ్‌లు', explore: 'అన్వేషించండి', profile: 'ప్రొఫైల్', settings: 'సెట్టింగ్‌లు', food: 'ఆహారం', activities: 'కార్యకలాపాలు', lostFound: 'పోయినవి & దొరికినవి', saved: 'సేవ్ చేసిన స్థలాలు', plan: 'కొత్త ప్రయాణాన్ని ప్లాన్ చేయండి' }, pages: { profile: 'ప్రొఫైల్', settings: 'సెట్టింగ్‌లు', planner: 'మీ ప్రయాణాన్ని ప్లాన్ చేయండి', trips: 'నా ప్రయాణాలు', explore: 'గమ్యస్థానాలను అన్వేషించండి' } },
  gu: { nav: { home: 'હોમ', trips: 'પ્રવાસો', assistant: 'સહાયક', bookings: 'બુકિંગ', explore: 'શોધો', profile: 'પ્રોફાઇલ', settings: 'સેટિંગ્સ', food: 'ભોજન', activities: 'પ્રવૃત્તિઓ', lostFound: 'ખોવાયેલું અને મળેલું', saved: 'સાચવેલ સ્થળો', plan: 'નવી સફર બનાવો' }, pages: { profile: 'પ્રોફાઇલ', settings: 'સેટિંગ્સ', planner: 'તમારી સફર બનાવો', trips: 'મારી સફરો', explore: 'ગંતવ્યો શોધો' } },
  kn: { nav: { home: 'ಮುಖಪುಟ', trips: 'ಪ್ರವಾಸಗಳು', assistant: 'ಸಹಾಯಕ', bookings: 'ಬುಕಿಂಗ್‌ಗಳು', explore: 'ಅನ್ವೇಷಿಸಿ', profile: 'ಪ್ರೊಫೈಲ್', settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು', food: 'ಆಹಾರ', activities: 'ಚಟುವಟಿಕೆಗಳು', lostFound: 'ಕಳೆದುಹೋದ ಮತ್ತು ಸಿಕ್ಕಿದ್ದು', saved: 'ಉಳಿಸಿದ ಸ್ಥಳಗಳು', plan: 'ಹೊಸ ಪ್ರವಾಸ ಯೋಜಿಸಿ' }, pages: { profile: 'ಪ್ರೊಫೈಲ್', settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು', planner: 'ನಿಮ್ಮ ಪ್ರವಾಸ ಯೋಜಿಸಿ', trips: 'ನನ್ನ ಪ್ರವಾಸಗಳು', explore: 'ತಾಣಗಳನ್ನು ಅನ್ವೇಷಿಸಿ' } },
  ml: { nav: { home: 'ഹോം', trips: 'യാത്രകൾ', assistant: 'സഹായി', bookings: 'ബുക്കിംഗുകൾ', explore: 'പര്യവേക്ഷണം', profile: 'പ്രൊഫൈൽ', settings: 'ക്രമീകരണങ്ങൾ', food: 'ഭക്ഷണം', activities: 'പ്രവർത്തനങ്ങൾ', lostFound: 'നഷ്ടപ്പെട്ടതും കണ്ടെത്തിയതും', saved: 'സൂക്ഷിച്ച സ്ഥലങ്ങൾ', plan: 'പുതിയ യാത്ര ആസൂത്രണം ചെയ്യുക' }, pages: { profile: 'പ്രൊഫൈൽ', settings: 'ക്രമീകരണങ്ങൾ', planner: 'നിങ്ങളുടെ യാത്ര ആസൂത്രണം ചെയ്യുക', trips: 'എന്റെ യാത്രകൾ', explore: 'ലക്ഷ്യസ്ഥാനങ്ങൾ പര്യവേക്ഷണം ചെയ്യുക' } }
};

i18n.use(initReactI18next).init({ resources: { en: { translation: en }, ...Object.fromEntries(Object.entries(localized).map(([code, translation]) => [code, { translation }])) }, lng: localStorage.getItem('atlas_language') ?? 'en', fallbackLng: 'en', interpolation: { escapeValue: false }, returnNull: false });
export default i18n;
